export const initialTeams = [
  {
    id: 1,
    name: "RRQ",
    image: "rrq",
    match_win: 10,
    match_lose: 5,
    game_win: 22,
    game_lose: 15,
  },
  {
    id: 2,
    name: "ONIC",
    image: "onic",
    match_win: 13,
    match_lose: 3,
    game_win: 27,
    game_lose: 9,
  },
  {
    id: 3,
    name: "EVOS",
    image: "evos",
    match_win: 6,
    match_lose: 9,
    game_win: 17,
    game_lose: 20,
  },
  {
    id: 4,
    name: "BTR",
    image: "btr",
    match_win: 6,
    match_lose: 9,
    game_win: 15,
    game_lose: 20,
  },
  {
    id: 5,
    name: "RBL",
    image: "rbl",
    match_win: 7,
    match_lose: 9,
    game_win: 17,
    game_lose: 21,
  },
  {
    id: 6,
    name: "DEWA",
    image: "dewa",
    match_win: 7,
    match_lose: 8,
    game_win: 16,
    game_lose: 20,
  },
  {
    id: 7,
    name: "GEEK",
    image: "geek",
    match_win: 10,
    match_lose: 6,
    game_win: 22,
    game_lose: 16,
  },
  {
    id: 8,
    name: "AE",
    image: "ae",
    match_win: 6,
    match_lose: 10,
    game_win: 17,
    game_lose: 23,
  },
  {
    id: 9,
    name: "AURA",
    image: "aura",
    match_win: 5,
    match_lose: 11,
    game_win: 14,
    game_lose: 23,
  },
];
